"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$character\
$directory\
$git_branch\
$git_status\
$dotnet\
$golang\
$haskell\
$lua\
$nodejs\
$php\
$python\
$rust\
$zig\
$cmd_duration\
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
truncation_length = 1
read_only = " 󰌾"

[dotnet]
symbol = " "

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '

[git_status]
style = 'bold yellow'

[golang]
symbol = " "

[haskell]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[os]
disabled = false
format = '[$symbol]($style)'
style = "bold cyan"

[os.symbols]
Arch = " "
Windows = "󰍲 "

[php]
symbol = " "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[zig]
symbol = " "
