hl.on("hyprland.start", function()
	hl.exec_cmd("waybar & swaync & hypridle & hyprpaper")
	hl.exec_cmd("hyprctl setcursor Sweet-cursors 24")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user start xdg-desktop-portal-hyprland")
end)
